### ISSUE TITLE
some advice

### ISSUE THREAD

**Issue by snowdream** [EverythingMe/openspace#4]
openspace is beautiful, it is my site: http://snowdream.github.io/
1.  add more config in the config.yml, like the name and the description of the website, the order of the projects(time,stars..asc,desc)
2. a default tag for all projects.
3. if the number of the projects is large,i wish them can be page up or page down,not list in just one web page.
4. add a copyright at the bottom of the website,and link to the project openspace.

**Comment by ranbena** [comment]
These are great suggestions. Creating separate issues.

**Comment by ranbena** [comment]
https://github.com/EverythingMe/openspace/issues/5
https://github.com/EverythingMe/openspace/issues/6
https://github.com/EverythingMe/openspace/issues/7

Regarding default tag - not sure what value that has.
Regarding paging - that could be problematic when filtering by tag. TBD.
